"""Detect and strip C2PA / AI-related metadata from raster images (stdlib).

Supported formats: PNG, JPEG, WebP, AVIF/HEIF (ISOBMFF), BMP, GIF, and TIFF
(classic and BigTIFF).
"""

from __future__ import annotations

import base64
import json
import os
import re
import struct
import sys
import urllib.error
import urllib.request
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import external_command
from common import atomic_write_bytes, classify_finding_confidence, which
from png_chunks import iter_png_chunks

SCRIPTS_DIR = Path(__file__).resolve().parent

OPTIONAL_TOOL_OUTPUT_LIMIT = 2 * 1024 * 1024
SYNTHID_OUTPUT_LIMIT = 2 * 1024 * 1024
#: Hard cap on the decompressed size of a PNG zTXt/iTXt text chunk.
#: Compressed chunks that would expand past this are treated as
#: decompression bombs: fail closed (no text entry) rather than allocating
#: unbounded output.
MAX_PNG_TEXT_BYTES = 8 * 1024 * 1024

PNG_SIG = b"\x89PNG\r\n\x1a\n"
JPEG_SOI = b"\xff\xd8"
WEBP_RIFF = b"RIFF"
WEBP_SIG = b"WEBP"
BMP_SIG = b"BM"
GIF_SIGS = (b"GIF87a", b"GIF89a")
TIFF_LE_SIG = b"II*\x00"
TIFF_BE_SIG = b"MM\x00*"
TIFF_LE_BIG_SIG = b"II+\x00"
TIFF_BE_BIG_SIG = b"MM\x00+"

DEFAULT_SYNTHID_SCORER_TIMEOUT = 60.0

# Chunk types / content patterns associated with C2PA / AI provenance
C2PA_MARKERS = (
    b"c2pa",
    b"C2PA",
    b"jumb",
    b"JUMB",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"http://ns.adobe.com/xmp/InstanceID/",  # not solely C2PA
)

AI_META_HINTS = (
    b"c2pa",
    b"C2PA",
    b"contentcredentials",
    b"ContentCredentials",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
)

# Well-known AI generator product/model names. These are matched ONLY
# against the values of generator-bearing PNG text-chunk keys (Software,
# Creator, parameters) — see _generator_product_hits — and deliberately
# kept out of the flat AI_META_HINTS blob scan: bare "Gemini", "Sora",
# or "Firefly" are ordinary words that can appear in captions, and only a
# generator field makes them evidence of AI provenance.
AI_GENERATOR_PRODUCTS = (
    b"ChatGPT",
    b"DALL-E",
    b"Midjourney",
    b"Stable Diffusion",
    b"SDXL",
    b"FLUX",
    b"DreamStudio",
    b"Leonardo AI",
    b"Leonardo.Ai",
    b"Craiyon",
    b"NovelAI",
    b"Ideogram",
    b"TensorArt",
    b"Recraft",
    b"Clipdrop",
    b"DeepAI",
    b"NightCafe",
    b"Bing Image Creator",
    b"Adobe Firefly",
    b"Firefly",
    b"Gemini",
    b"Imagen",
    b"Grok",
    b"Sora",
    b"Veo",
    b"Kling",
    b"Runway",
    b"Luma",
    b"Qwen",
    b"GPT-4",
    b"GPT-5",
)

# PNG text-chunk keys whose value can name the generating model/tool.
# tEXt/iTXt "Software" and "Creator" are the classic generator fields;
# "parameters" is what Stable Diffusion WebUI writes with the full
# generation string. Values of other keys (Comment, Description, Title,
# ...) are free text and are never scanned for product names.
_GENERATOR_TEXT_KEYS = ("software", "creator", "parameters")


@dataclass
class ImageInspectReport:
    path: str
    format: str  # png | jpeg | webp | avif | heif | bmp | gif | tiff | unknown
    has_c2pa: bool
    has_ai_metadata: bool
    findings: list[str] = field(default_factory=list)
    tools: dict[str, Any] = field(default_factory=dict)
    synthid: dict[str, Any] | None = None
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "format": self.format,
            "has_c2pa": self.has_c2pa,
            "has_ai_metadata": self.has_ai_metadata,
            "findings": self.findings,
            "findings_confidence": [classify_finding_confidence(f) for f in self.findings],
            "tools": self.tools,
            "synthid": self.synthid,
            "notes": self.notes,
        }


def detect_format(data: bytes) -> str:
    if data.startswith(PNG_SIG):
        return "png"
    if data.startswith(JPEG_SOI):
        return "jpeg"
    if len(data) >= 12 and data[:4] == WEBP_RIFF and data[8:12] == WEBP_SIG:
        return "webp"
    if data[:2] == BMP_SIG:
        return "bmp"
    if data[:6] in GIF_SIGS:
        return "gif"
    if data[:4] in (TIFF_LE_SIG, TIFF_BE_SIG, TIFF_LE_BIG_SIG, TIFF_BE_BIG_SIG):
        return "tiff"
    from heif_meta import detect_heif  # lazy: avoids module-level cycle

    return detect_heif(data)  # 'heif' | 'avif' | 'unknown'


def _contains_any(blob: bytes, needles: tuple[bytes, ...]) -> list[str]:
    found = []
    lower = blob.lower()
    for n in needles:
        if n.lower() in lower:
            try:
                found.append(n.decode("ascii", errors="replace"))
            except Exception:
                found.append(repr(n))
    return found


def _zlib_decompress_bounded(data: bytes, max_bytes: int = MAX_PNG_TEXT_BYTES) -> bytes | None:
    """Decompress a zlib stream with an explicit output cap.

    Returns the decompressed bytes when the stream is valid and its output
    fits in *max_bytes*; returns None for corrupt/truncated streams and when
    the output would exceed the cap. None means "no usable text": callers
    fail closed (skip the chunk) instead of allocating unbounded memory.
    """
    decompressor = zlib.decompressobj()
    out = bytearray()
    remaining = data
    while True:
        budget = max_bytes + 1 - len(out)
        if budget <= 0:
            return None
        try:
            out += decompressor.decompress(remaining, budget)
        except zlib.error:
            return None
        if len(out) > max_bytes:
            return None
        if decompressor.eof:
            return bytes(out)
        if not decompressor.unconsumed_tail:
            return None
        remaining = decompressor.unconsumed_tail


def _png_text_entries(payload: bytes, ctype: bytes) -> list[tuple[str, str]]:
    """Parse a PNG text-chunk payload into (key, value) pairs.

    Handles tEXt (latin-1), zTXt (zlib-compressed text), and iTXt
    (UTF-8, optionally compressed). Malformed or undecodable chunks
    yield whatever pairs are recoverable; nothing is raised.
    """
    entries: list[tuple[str, str]] = []
    if ctype == b"tEXt":
        key, sep, text = payload.partition(b"\x00")
        if sep:
            entries.append(
                (
                    key.decode("latin-1", errors="replace"),
                    text.decode("latin-1", errors="replace"),
                )
            )
    elif ctype == b"zTXt":
        key, sep, rest = payload.partition(b"\x00")
        if not sep or len(rest) < 2:
            return entries
        text = _zlib_decompress_bounded(rest[1:])
        if text is None:
            return entries
        entries.append(
            (
                key.decode("latin-1", errors="replace"),
                text.decode("latin-1", errors="replace"),
            )
        )
    elif ctype == b"iTXt":
        key, sep, rest = payload.partition(b"\x00")
        if not sep or len(rest) < 4:
            return entries
        comp_flag = rest[0]
        rest = rest[2:]  # skip compression flag + method
        _lang, sep2, rest = rest.partition(b"\x00")
        if not sep2:
            return entries
        _tkey, sep3, text = rest.partition(b"\x00")
        if not sep3:
            return entries
        if comp_flag == 1:
            text = _zlib_decompress_bounded(text)
            if text is None:
                return entries
        entries.append(
            (
                key.decode("latin-1", errors="replace"),
                text.decode("utf-8", errors="replace"),
            )
        )
    return entries


def _generator_product_hits(entries: list[tuple[str, str]]) -> list[str]:
    """Product-name hits scoped to generator-bearing text-chunk keys.

    Returns labels like "Software=ChatGPT" (one per matching product).
    Matching is a case-insensitive substring check on the value, mirroring
    _contains_any, but only for _GENERATOR_TEXT_KEYS values.
    """
    hits: list[str] = []
    for key, value in entries:
        if key.strip().lower() not in _GENERATOR_TEXT_KEYS:
            continue
        low = value.lower()
        for product in AI_GENERATOR_PRODUCTS:
            label = product.decode("ascii", errors="replace")
            if label.lower() in low:
                hits.append(f"{key.strip()}={label}")
    return hits


def _text_chunk_is_ai(payload: bytes, ctype: bytes) -> bool:
    """True when a PNG text chunk carries AI/C2PA markers.

    Flat markers (AI_META_HINTS + C2PA_MARKERS) match anywhere in the
    payload; generator product names only match generator-bearing key
    values (see _generator_product_hits).
    """
    if _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
        return True
    return bool(_generator_product_hits(_png_text_entries(payload, ctype)))


def inspect_png(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if not data.startswith(PNG_SIG):
        return False, False, ["not a PNG"]
    try:
        for chunk in iter_png_chunks(data):
            ctype = chunk.kind
            name = ctype.decode("latin-1", errors="replace")
            if ctype in (b"caBX", b"juMB", b"jumb") or ctype.startswith(b"c2"):
                has_c2pa = True
                findings.append(f"PNG chunk {name} (possible C2PA container)")
            if ctype in (b"tEXt", b"zTXt", b"iTXt", b"eXIf"):
                payload = bytes(chunk.payload)
                hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
                product_hits = (
                    _generator_product_hits(_png_text_entries(payload, ctype))
                    if ctype in (b"tEXt", b"zTXt", b"iTXt")
                    else []
                )
                if hits or product_hits:
                    has_ai = True
                    if any(hit.lower() in ("c2pa", "contentcredentials", "jumb") for hit in hits):
                        has_c2pa = True
                    parts = [", ".join(hits[:8])] if hits else []
                    if product_hits:
                        parts.append(f"AI generator ({', '.join(product_hits[:8])})")
                    findings.append(f"PNG {name}: {'; '.join(parts)}")
    except ValueError as error:
        findings.append(str(error))
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def inspect_avif(data: bytes) -> tuple[bool, bool, list[str]]:
    """Inspect AVIF (ISO-BMFF) for C2PA/JUMBF boxes and AI-marked Exif/XMP items."""
    from heif_meta import inspect_heif

    has_c2pa, has_ai, findings, _ = inspect_heif(data)
    return has_c2pa, has_ai, findings


def inspect_heic(data: bytes) -> tuple[bool, bool, list[str]]:
    """Inspect HEIC/HEIF (ISO-BMFF) for C2PA/JUMBF boxes and AI-marked Exif/XMP items."""
    from heif_meta import inspect_heif

    has_c2pa, has_ai, findings, _ = inspect_heif(data)
    return has_c2pa, has_ai, findings


def strip_avif(data: bytes, *, strip_all: bool = True) -> tuple[bytes, list[str]]:
    """Neutralize C2PA/AI metadata in AVIF in place (offsets preserved; pixels untouched)."""
    from heif_meta import neutralize_heif

    return neutralize_heif(data, strip_all_metadata=strip_all)


def strip_heic(data: bytes, *, strip_all: bool = True) -> tuple[bytes, list[str]]:
    """Neutralize C2PA/AI metadata in HEIC/HEIF in place (offsets preserved; pixels untouched)."""
    from heif_meta import neutralize_heif

    return neutralize_heif(data, strip_all_metadata=strip_all)


def inspect_jpeg(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if not data.startswith(JPEG_SOI):
        return False, False, ["not a JPEG"]
    i = 2
    n = len(data)
    while i + 4 <= n:
        if data[i] != 0xFF:
            i += 1
            continue
        # skip fill
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1
        if marker in (0xD8, 0xD9):  # SOI/EOI
            continue
        if marker == 0xDA:  # SOS — image data follows
            break
        if marker >= 0xD0 and marker <= 0xD7:  # RSTn
            continue
        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i : i + 2])[0]
        if seglen < 2 or i + seglen > n:
            findings.append(f"bad segment length at marker 0x{marker:02X}")
            break
        payload = data[i + 2 : i + seglen]
        i += seglen

        # APP11 is only C2PA when the payload actually carries JUMBF/C2PA
        # markers; APP11 itself has other legitimate uses.
        if marker in (0xE1, 0xE2, 0xED, 0xEE, 0xEB):  # APP1,2,13,14,11
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(
                    h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth") for h in hits
                ):
                    has_c2pa = True
                findings.append(f"JPEG APP{marker - 0xE0}: {', '.join(hits[:8])}")

    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def run_optional_tools(path: Path) -> dict[str, Any]:
    tools: dict[str, Any] = {}
    c2patool = which("c2patool")
    if c2patool:
        try:
            result = external_command.run_command(
                [c2patool, str(path)],
                timeout=30,
                output_limit=OPTIONAL_TOOL_OUTPUT_LIMIT,
            )
            output = result.stdout_text + result.stderr_text
            if result.stdout_truncated or result.stderr_truncated:
                tools["c2patool"] = {
                    "available": True,
                    "returncode": result.returncode,
                    "error": "c2patool output exceeded safety limit",
                }
            else:
                low = output.lower()
                no_manifest = "no claim" in low or "no jumbf" in low
                tools["c2patool"] = {
                    "available": True,
                    "returncode": result.returncode,
                    "snippet": output[:2000],
                    "has_manifest": ("claim" in low or "c2pa" in low or "manifest" in low)
                    and not no_manifest,
                }
        except Exception as error:
            tools["c2patool"] = {"available": True, "error": str(error)}
    else:
        tools["c2patool"] = {"available": False}

    exiftool = which("exiftool")
    if exiftool:
        try:
            result = external_command.run_command(
                [exiftool, "-G1", "-a", "-s", str(path)],
                timeout=30,
                output_limit=OPTIONAL_TOOL_OUTPUT_LIMIT,
            )
            if result.stdout_truncated or result.stderr_truncated:
                tools["exiftool"] = {
                    "available": True,
                    "error": "exiftool output exceeded safety limit",
                }
            else:
                interesting = [
                    line
                    for line in result.stdout_text.splitlines()
                    if re.search(
                        r"c2pa|content.?credential|AIGC|digitalSource|XMP|EXIF|IPTC|jumb",
                        line,
                        re.I,
                    )
                ]
                tools["exiftool"] = {
                    "available": True,
                    "interesting_lines": interesting[:50],
                }
        except Exception as error:
            tools["exiftool"] = {"available": True, "error": str(error)}
    else:
        tools["exiftool"] = {"available": False}
    return tools


def _synthid_score_http(
    path: Path, base_url: str, api_key: str, timeout: float
) -> dict[str, Any] | None:
    """Score *path* via the HTTP sidecar (synthid_score_server.py)."""
    try:
        data = path.read_bytes()
    except OSError as e:
        return {"available": False, "error": f"cannot read {path}: {e}"}
    body = json.dumps({"file": base64.b64encode(data).decode("ascii")}).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    if urlparse(base_url).scheme not in ("http", "https"):
        return {"available": False, "error": f"refusing non-http(s) scorer endpoint: {base_url}"}
    # S310: URL scheme is restricted to http/https just above.
    req = urllib.request.Request(  # noqa: S310
        base_url.rstrip("/") + "/score",
        data=body,
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            payload = json.loads(resp.read().decode("utf-8"))
    except (
        urllib.error.HTTPError,
        urllib.error.URLError,
        TimeoutError,
        OSError,
        json.JSONDecodeError,
    ) as e:
        return {"available": False, "error": f"SynthID scorer sidecar unreachable: {e}"}
    if not isinstance(payload, dict):
        return {"available": False, "error": "bad scorer sidecar response"}
    return payload


def run_synthid_score(
    path: Path,
    upstream_dir: str | None = None,
) -> dict[str, Any] | None:
    """Run the optional reverse-SynthID scorer.

    Uses the HTTP sidecar when WATERMARKS_SYNTHID_SCORER_URL is set,
    otherwise a subprocess against a local checkout. Returns None when the
    scorer is not configured; a dict with "available": False and an "error"
    when it is configured but unavailable (e.g. exit 3), so callers can
    distinguish "not scored" from "scored and clean".
    """
    scorer_url = os.environ.get("WATERMARKS_SYNTHID_SCORER_URL", "").strip()
    if scorer_url:
        api_key = os.environ.get("WATERMARKS_SYNTHID_SCORER_API_KEY", "").strip()
        try:
            timeout = float(os.environ.get("WATERMARKS_SYNTHID_SCORER_TIMEOUT", "60"))
        except ValueError:
            timeout = DEFAULT_SYNTHID_SCORER_TIMEOUT
        return _synthid_score_http(path, scorer_url, api_key, timeout)
    if upstream_dir is None:
        upstream_dir = os.environ.get("REVERSE_SYNTHID_DIR")
    if not upstream_dir:
        return None

    script = SCRIPTS_DIR / "score_synthid.py"
    cmd = [
        sys.executable,
        str(script),
        str(path),
        "--upstream-dir",
        str(upstream_dir),
        "--json",
    ]
    try:
        result = external_command.run_command(
            cmd,
            timeout=180,
            output_limit=SYNTHID_OUTPUT_LIMIT,
        )
    except Exception as error:
        return {"available": False, "error": str(error)}

    if result.stdout_truncated or result.stderr_truncated:
        return {"available": False, "error": "scorer output exceeded safety limit"}
    if result.returncode == 3:
        return None
    if result.returncode != 0:
        return {"available": False, "error": result.stderr_text.strip()[:2000]}
    try:
        return json.loads(result.stdout_text or "{}")
    except json.JSONDecodeError as error:
        return {"available": False, "error": f"bad scorer JSON: {error}"}


def inspect_image(
    path: Path,
    synthid_dir: str | None = None,
) -> ImageInspectReport:
    data = path.read_bytes()
    fmt = detect_format(data)
    notes: list[str] = []
    if fmt in ("heif", "avif"):
        has_c2pa, has_ai, findings = inspect_heic(data)
    elif fmt == "png":
        has_c2pa, has_ai, findings = inspect_png(data)
    elif fmt == "jpeg":
        has_c2pa, has_ai, findings = inspect_jpeg(data)
    elif fmt == "webp":
        has_c2pa, has_ai, findings = inspect_webp(data)
    elif fmt == "bmp":
        has_c2pa, has_ai, findings = inspect_bmp(data)
    elif fmt == "gif":
        has_c2pa, has_ai, findings = inspect_gif(data)
    elif fmt == "tiff":
        has_c2pa, has_ai, findings = inspect_tiff(data)
    else:
        has_c2pa, has_ai, findings = False, False, ["unsupported format"]
        notes.append(f"format '{fmt}' is not inspected")

    tools = run_optional_tools(path)
    # Elevate flags from tools
    ct = tools.get("c2patool") or {}
    if ct.get("has_manifest"):
        has_c2pa = True
        findings.append("c2patool reports a C2PA-related manifest")

    return ImageInspectReport(
        path=str(path),
        format=fmt,
        has_c2pa=has_c2pa,
        has_ai_metadata=has_ai,
        findings=findings,
        tools=tools,
        notes=notes,
        synthid=(run_synthid_score(path, synthid_dir) if fmt in ("png", "jpeg") else None),
    )


def strip_png(data: bytes, *, strip_all_text: bool = True) -> tuple[bytes, list[str]]:
    actions: list[str] = []
    out = bytearray(PNG_SIG)
    for chunk in iter_png_chunks(data, allow_trailing_data=True):
        ctype = chunk.kind
        payload = chunk.payload
        name = ctype.decode("latin-1", errors="replace")

        drop = False
        if ctype == b"caBX" or ctype.startswith(b"c2"):
            drop = True
            actions.append(f"drop chunk {name}")
        elif ctype == b"eXIf" or ctype in (b"tEXt", b"zTXt", b"iTXt"):
            if strip_all_text or _text_chunk_is_ai(bytes(payload), ctype):
                drop = True
                actions.append(f"drop chunk {name}")
        elif _contains_any(ctype + bytes(payload), C2PA_MARKERS) and ctype not in (
            b"IHDR",
            b"IDAT",
            b"IEND",
            b"PLTE",
            b"tRNS",
            b"gAMA",
            b"pHYs",
            b"sRGB",
            b"cHRM",
            b"iCCP",
        ):
            drop = True
            actions.append(f"drop chunk {name} (C2PA marker in payload)")

        if not drop:
            out.extend(chunk.raw)
    if not actions:
        actions.append("no PNG metadata chunks removed (already clean or none matched)")
    return bytes(out), actions


#: Keyword of the truthful "cleaned by wm" replacement marker (F4).
WMCT_KEYWORD = "wmCt"
#: Human-readable marker text; kept short and stable.
WMCT_TEXT = '{"tool":"wm","cleaned":true}'


def add_wmct_marker(data: bytes, text: str = WMCT_TEXT) -> bytes:
    """Inject a ``wmCt`` tEXt chunk into a PNG, before IEND.

    F4 gives users an optional *replacement* provenance marker (strip-without-
    replacement stays the frictionless default).  The marker is a plain tEXt
    chunk whose keyword ``wmCt`` records that this output was cleaned by wm —
    parseable, truthful, and never mistaken for vendor C2PA.
    """
    if not data.startswith(PNG_SIG):
        raise ValueError("wmCt marker requires PNG input")
    keyword = WMCT_KEYWORD.encode("latin-1")
    payload = keyword + b"\x00" + text.encode("utf-8")
    marker_chunk = struct.pack(">I", len(payload)) + keyword + payload
    marker_chunk += struct.pack(">I", zlib.crc32(payload, zlib.crc32(keyword)) & 0xFFFFFFFF)

    # Rebuild the PNG, inserting the marker immediately before the terminal
    # IEND.  Iterating validated chunks is robust regardless of the IEND CRC.
    out = bytearray(PNG_SIG)
    for chunk in iter_png_chunks(data, allow_trailing_data=True):
        if chunk.kind == b"IEND":
            out.extend(marker_chunk)
        out.extend(chunk.raw)
    return bytes(out)


def _find_jpeg_eoi(data: bytes, start: int) -> int | None:
    """Locate an unstuffed EOI marker in entropy-coded JPEG data."""
    i = start
    while i + 1 < len(data):
        if data[i] != 0xFF:
            i += 1
            continue
        j = i + 1
        while j < len(data) and data[j] == 0xFF:
            j += 1
        if j >= len(data):
            return None
        marker = data[j]
        if marker == 0x00 or 0xD0 <= marker <= 0xD7:
            i = j + 1
            continue
        if marker == 0xD9:
            return j - 1
        i = j + 1
    return None


def strip_jpeg(data: bytes, *, strip_all_app: bool = True) -> tuple[bytes, list[str]]:
    if not data.startswith(JPEG_SOI):
        raise ValueError("not JPEG")
    actions: list[str] = []
    out = bytearray(JPEG_SOI)
    i = 2
    n = len(data)
    saw_eoi = False
    while i < n:
        if data[i] != 0xFF:
            raise ValueError(f"malformed JPEG marker stream at offset {i}")
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1

        if marker == 0xD9:  # EOI
            out.extend(b"\xff\xd9")
            saw_eoi = True
            break
        if marker == 0xD8:  # nested SOI?
            continue
        if 0xD0 <= marker <= 0xD7:
            out.extend(bytes([0xFF, marker]))
            continue
        if marker == 0xDA:  # SOS — copy through end
            # need length of SOS header then entropy-coded data to EOI
            if i + 2 > n:
                raise ValueError("truncated JPEG SOS length")
            segment_length = struct.unpack(">H", data[i : i + 2])[0]
            if segment_length < 2 or i + segment_length > n:
                raise ValueError("truncated JPEG SOS header")
            # Preserve the complete entropy-coded stream only after locating an
            # unstuffed EOI marker; FF00 and restart markers are scan data.
            scan_start = i + segment_length
            eoi = _find_jpeg_eoi(data, scan_start)
            if eoi is None:
                raise ValueError("JPEG scan has no complete EOI marker")
            out.extend(b"\xff\xda")
            out.extend(data[i : eoi + 2])
            actions.append("preserved entropy-coded scan through EOI")
            saw_eoi = True
            break

        if i + 2 > n:
            raise ValueError(f"truncated JPEG segment length at marker 0x{marker:02X}")
        seglen = struct.unpack(">H", data[i : i + 2])[0]
        if seglen < 2 or i + seglen > n:
            raise ValueError(f"truncated JPEG segment at marker 0x{marker:02X}")
        payload = data[i + 2 : i + seglen]
        next_i = i + seglen

        # APP0 is JFIF — keep for compatibility unless full strip of all APP
        keep = False
        drop = False
        if 0xE0 <= marker <= 0xEF:  # APPn
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            app11_is_c2pa = marker == 0xEB and any(
                h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth") for h in hits
            )
            if app11_is_c2pa:
                drop = True
                actions.append("drop APP11 (C2PA/JUMBF)")
            elif strip_all_app and marker != 0xE0:
                # keep APP0 (JFIF) by default
                drop = True
                actions.append(f"drop APP{marker - 0xE0}")
            elif hits:
                drop = True
                actions.append(f"drop APP{marker - 0xE0} (AI/C2PA markers)")
            else:
                keep = True
        elif marker == 0xFE:  # COM
            if strip_all_app or _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append("drop COM comment")
            else:
                keep = True
        else:
            keep = True

        if keep and not drop:
            out.extend(bytes([0xFF, marker]))
            out.extend(data[i : i + seglen])
        i = next_i

    if not saw_eoi:
        raise ValueError("JPEG has no complete EOI marker")
    if not actions:
        actions.append("no JPEG APP segments removed")
    return bytes(out), actions


# ---------------------------------------------------------------------------
# WebP
# ---------------------------------------------------------------------------


def _webp_chunks(data: bytes) -> tuple[list[tuple[bytes, bytes, bytes]], list[str]]:
    if detect_format(data) != "webp":
        return [], ["not a WebP"]

    notes: list[str] = []
    declared_size = struct.unpack("<I", data[4:8])[0]
    if declared_size + 8 != len(data):
        notes.append(f"RIFF size mismatch: header={declared_size + 8} actual={len(data)}")

    chunks: list[tuple[bytes, bytes, bytes]] = []
    pos = 12
    while pos + 8 <= len(data):
        fourcc = data[pos : pos + 4]
        length = struct.unpack("<I", data[pos + 4 : pos + 8])[0]
        payload_start = pos + 8
        payload_end = payload_start + length
        padded_end = payload_end + (length & 1)
        if padded_end > len(data):
            name = fourcc.decode("latin-1", errors="replace")
            notes.append(f"truncated WebP chunk {name}")
            break
        chunks.append((fourcc, data[payload_start:payload_end], data[payload_end:padded_end]))
        pos = padded_end
    if pos != len(data) and not any("truncated" in note for note in notes):
        notes.append(f"trailing WebP bytes: {len(data) - pos}")
    return chunks, notes


def inspect_webp(data: bytes) -> tuple[bool, bool, list[str]]:
    chunks, findings = _webp_chunks(data)
    if not chunks and findings == ["not a WebP"]:
        return False, False, findings

    has_c2pa = False
    has_ai = False
    for fourcc, payload, _padding in chunks:
        name = fourcc.decode("latin-1", errors="replace")
        if fourcc.upper() == b"C2PA":
            has_c2pa = True
            has_ai = True
            findings.append("WebP C2PA chunk")
            continue
        if fourcc in (b"XMP ", b"EXIF"):
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(
                    hit.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                    for hit in hits
                ):
                    has_c2pa = True
                findings.append(f"WebP {name}: {', '.join(hits[:8])}")
    return has_c2pa, has_ai or has_c2pa, findings


def strip_webp(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    chunks, notes = _webp_chunks(data)
    if not chunks and notes == ["not a WebP"]:
        raise ValueError("not WebP")
    if notes:
        raise ValueError("malformed WebP: " + "; ".join(notes))

    actions: list[str] = []
    kept: list[tuple[bytes, bytes, bytes]] = []
    removed_flags = 0
    metadata_flags = {b"ICCP": 0x20, b"EXIF": 0x08, b"XMP ": 0x04}

    for fourcc, payload, padding in chunks:
        drop = fourcc.upper() == b"C2PA"
        if fourcc in metadata_flags:
            drop = strip_all_metadata or bool(_contains_any(payload, AI_META_HINTS + C2PA_MARKERS))
        if drop:
            name = fourcc.decode("latin-1", errors="replace")
            actions.append(f"drop WebP chunk {name}")
            removed_flags |= metadata_flags.get(fourcc, 0)
        else:
            kept.append((fourcc, payload, padding))

    body = bytearray(WEBP_SIG)
    for fourcc, payload, padding in kept:
        chunk = payload
        if fourcc == b"VP8X" and len(chunk) >= 1 and removed_flags:
            chunk = bytes([chunk[0] & ~removed_flags]) + chunk[1:]
        body.extend(fourcc)
        body.extend(struct.pack("<I", len(chunk)))
        body.extend(chunk)
        body.extend(padding if len(chunk) & 1 else b"")

    if not actions:
        actions.append("no WebP metadata chunks removed (already clean or none matched)")
    return WEBP_RIFF + struct.pack("<I", len(body)) + bytes(body), actions


# ---------------------------------------------------------------------------
# BMP
# ---------------------------------------------------------------------------


def _bmp_payload_extent(data: bytes) -> tuple[int, int] | None:
    """Return (pixel_offset, pixel_size) for a BMP, or None."""
    if len(data) < 30 or data[:2] != BMP_SIG:
        return None
    pixel_offset = struct.unpack("<I", data[10:14])[0]
    dib_size = struct.unpack("<I", data[14:18])[0]
    if dib_size < 40 or 14 + dib_size > len(data):
        return None
    width = struct.unpack("<i", data[18:22])[0]
    height = struct.unpack("<i", data[22:26])[0]
    bpp = struct.unpack("<H", data[28:30])[0]
    compression = struct.unpack("<I", data[30:34])[0]
    size_image = struct.unpack("<I", data[34:38])[0]
    if width <= 0 or bpp == 0 or pixel_offset > len(data):
        return None
    if compression == 0:  # BI_RGB
        row_size = ((width * bpp + 31) // 32) * 4
        size = row_size * abs(height)
    elif size_image:
        size = size_image
    else:
        return None
    return pixel_offset, size


def _bmp_trailing(data: bytes) -> bytes:
    """Bytes after the image payload, which is where non-standard BMP metadata lives."""
    extent = _bmp_payload_extent(data)
    if extent is None:
        return b""
    pixel_offset, size = extent
    end = pixel_offset + size
    return data[end:] if end < len(data) else b""


def inspect_bmp(data: bytes) -> tuple[bool, bool, list[str]]:
    """Inspect a BMP for trailing (non-standard) metadata."""
    findings: list[str] = []
    if len(data) < 14 or data[:2] != BMP_SIG:
        return False, False, ["not a BMP"]
    trailing = _bmp_trailing(data)
    has_c2pa = False
    has_ai = False
    if trailing:
        hits = _contains_any(trailing, AI_META_HINTS + C2PA_MARKERS)
        if hits:
            has_ai = True
            if any(
                h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth") for h in hits
            ):
                has_c2pa = True
            findings.append(f"BMP trailing metadata: {', '.join(hits[:6])}")
        else:
            findings.append(f"BMP has {len(trailing)} unrecognized trailing byte(s)")
    else:
        findings.append("BMP has no metadata (header-only raster format)")
    return has_c2pa, has_ai or has_c2pa, findings


def strip_bmp(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    """Strip trailing non-image bytes from a BMP and fix the file-size field."""
    if len(data) < 14 or data[:2] != BMP_SIG:
        raise ValueError("not BMP")
    extent = _bmp_payload_extent(data)
    if extent is None:
        return data, ["BMP header not fully parsed; left unchanged"]
    pixel_offset, size = extent
    end = pixel_offset + size
    if end >= len(data):
        return data, ["no BMP trailing metadata to strip"]
    trailing = data[end:]
    hits = _contains_any(trailing, AI_META_HINTS + C2PA_MARKERS)
    if not strip_all_metadata and not hits:
        return data, ["BMP trailing bytes kept (keep-non-ai-metadata)"]
    out = bytearray(data[:end])
    out[2:6] = struct.pack("<I", end)
    reason = f" ({', '.join(hits[:4])})" if hits else ""
    return bytes(out), [f"drop {len(trailing)} BMP trailing byte(s){reason}"]


# ---------------------------------------------------------------------------
# GIF
# ---------------------------------------------------------------------------


def _gif_extension_info(data: bytes, start: int, n: int) -> tuple[int, int, bytes] | None:
    """Return (end, label, payload) for the extension block at *start* (0x21)."""
    if start + 2 > n:
        return None
    label = data[start + 1]
    pos = start + 2
    payload = bytearray()
    while pos < n:
        size = data[pos]
        pos += 1
        if size == 0:
            return pos, label, bytes(payload)
        if pos + size > n:
            return None
        payload.extend(data[pos : pos + size])
        pos += size
    return None


def _gif_image_end(data: bytes, start: int, n: int) -> int | None:
    """Return the offset just past the image block starting at *start* (0x2C)."""
    if start + 10 > n:
        return None
    pos = start + 10
    if pos >= n:
        return None
    lct_size = data[pos] & 0x07
    pos += 1
    if lct_size:
        pos += 3 * (1 << lct_size)
    if pos >= n:
        return None
    pos += 1  # LZW min code size
    while pos < n:
        size = data[pos]
        pos += 1
        if size == 0:
            return pos
        if pos + size > n:
            return None
        pos += size
    return None


def inspect_gif(data: bytes) -> tuple[bool, bool, list[str]]:
    """Inspect GIF comment/application extensions for AI/C2PA markers."""
    findings: list[str] = []
    if data[:6] not in GIF_SIGS:
        return False, False, ["not a GIF"]
    n = len(data)
    has_c2pa = False
    has_ai = False
    pos = 6
    while pos + 1 <= n:
        block = data[pos]
        if block == 0x21:
            info = _gif_extension_info(data, pos, n)
            if info is None:
                findings.append("truncated GIF extension block")
                break
            end, label, payload = info
            if label == 0xFE:
                hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
                if hits:
                    has_ai = True
                    if any(
                        h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                        for h in hits
                    ):
                        has_c2pa = True
                    findings.append(f"GIF comment: {', '.join(hits[:6])}")
            elif label == 0xFF:
                if payload[:11] == b"XMP DataXMP":
                    hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
                    if hits:
                        has_ai = True
                        if any(
                            h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                            for h in hits
                        ):
                            has_c2pa = True
                        findings.append(f"GIF XMP app: {', '.join(hits[:6])}")
                else:
                    hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
                    if hits:
                        has_ai = True
                        findings.append(f"GIF application ext: {', '.join(hits[:6])}")
            pos = end
        elif block == 0x2C:
            end = _gif_image_end(data, pos, n)
            if end is None:
                findings.append("truncated GIF image block")
                break
            pos = end
        else:
            pos += 1

    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def strip_gif(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    """Strip GIF comment + XMP/unknown application extensions (in-place, offsets preserved)."""
    if data[:6] not in GIF_SIGS:
        raise ValueError("not GIF")
    n = len(data)
    out = bytearray(data[:6])
    actions: list[str] = []
    pos = 6
    while pos + 1 <= n:
        block = data[pos]
        if block == 0x21:
            info = _gif_extension_info(data, pos, n)
            if info is None:
                out.extend(data[pos:])
                break
            end, label, payload = info
            marker_hit = bool(_contains_any(payload, AI_META_HINTS + C2PA_MARKERS))
            drop = False
            name = "extension"
            if label == 0xFE:
                name = "comment"
                drop = strip_all_metadata or marker_hit
            elif label == 0xFF:
                if payload[:11] == b"XMP DataXMP":
                    name = "XMP application"
                    drop = strip_all_metadata or marker_hit
                elif payload[:11] == b"NETSCAPE2.0" or payload[:3] == b"ICCS":
                    name = "application"
                    drop = False
                else:
                    name = "application"
                    drop = strip_all_metadata or marker_hit
            if drop:
                actions.append(f"drop GIF {name} extension")
            else:
                out.extend(data[pos:end])
            pos = end
        elif block == 0x2C:
            end = _gif_image_end(data, pos, n)
            if end is None:
                out.extend(data[pos:])
                break
            out.extend(data[pos:end])
            pos = end
        else:
            out.extend(data[pos : pos + 1])
            pos += 1

    if not actions:
        actions.append("no GIF metadata blocks removed (already clean or none matched)")
    return bytes(out), actions


# ---------------------------------------------------------------------------
# TIFF (classic + BigTIFF)
# ---------------------------------------------------------------------------


_TIFF_TYPE_SIZES = {1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8, 11: 4, 12: 8}

# Provenance / descriptive metadata tags stripped when cleaning TIFF.
_TIFF_META_TAG_NAMES = {
    269: "DocumentName",
    270: "ImageDescription",
    271: "Make",
    272: "Model",
    305: "Software",
    306: "DateTime",
    315: "Artist",
    316: "HostComputer",
    33432: "Copyright",
    40091: "XPTitle",
    40092: "XPComment",
    40093: "XPAuthor",
    40094: "XPKeywords",
    40095: "XPSubject",
    700: "XMP",
    33723: "IPTC/NAA",
    34377: "Photoshop",
    34665: "ExifIFD",
    34853: "GPSInfo",
    37500: "MakerNote",
}

_TIFF_DROP_TAGS = frozenset(_TIFF_META_TAG_NAMES)

# Structural tags that must survive even when their payload looks marker-ish.
_TIFF_KEEP_TAGS = frozenset(
    {
        254,
        255,
        256,
        257,
        258,
        259,
        262,
        263,
        264,
        265,
        266,
        273,
        274,
        277,
        278,
        279,
        282,
        283,
        284,
        285,
        286,
        287,
        288,
        289,
        290,
        291,
        292,
        293,
        294,
        295,
        296,
        297,
        301,
        302,
        304,
        320,
        321,
        322,
        323,
        324,
        325,
        326,
        327,
        328,
        329,
        330,
        331,
        332,
        333,
        334,
        336,
        338,
        339,
        340,
        341,
        342,
        343,
        344,
        345,
        346,
        347,
        512,
        513,
        514,
        515,
        516,
        517,
        518,
        519,
        520,
        521,
        529,
        530,
        531,
        532,
        533,
        33421,
        33422,
        33423,
        34675,
        34676,
        *range(50706, 50742),  # DNG structural tags
    }
)

MAX_TIFF_IFDS = 4096


def _tiff_layout(data: bytes) -> tuple[str, bool] | None:
    """Return (byte_order, bigtiff) for a classic or BigTIFF, else None."""
    if data[:2] == b"II" and data[2:4] == b"*\x00":
        return "<", False
    if data[:2] == b"MM" and data[2:4] == b"\x00*":
        return ">", False
    if data[:2] == b"II" and data[2:4] == b"+\x00":
        return "<", True
    if data[:2] == b"MM" and data[2:4] == b"\x00+":
        return ">", True
    return None


def _parse_tiff_ifds(data: bytes) -> tuple[str, bool, dict[int, dict[str, Any]]]:
    """Parse every reachable TIFF IFD (classic 12-byte or BigTIFF 20-byte entries).

    Returns (byte_order, bigtiff, {offset: {count, entries, next, block_len}}).
    Each entry is {tag, type, count, value (inline field bytes), byte_size,
    value_offset}; value_offset is None when the value is inline. Cycle-
    protected with a hard cap on the number of IFDs.
    """
    layout = _tiff_layout(data)
    if layout is None:
        raise ValueError("not a TIFF")
    bo, bigtiff = layout
    n = len(data)
    count_len = 8 if bigtiff else 2
    off_len = 8 if bigtiff else 4
    entry_size = 20 if bigtiff else 12
    header_size = 16 if bigtiff else 8
    count_fmt = bo + ("Q" if bigtiff else "H")
    off_fmt = bo + ("Q" if bigtiff else "I")
    if n < header_size:
        return bo, bigtiff, {}
    first = struct.unpack(off_fmt, data[header_size - off_len : header_size])[0]
    if first == 0 or first + count_len > n:
        return bo, bigtiff, {}
    ifds: dict[int, dict[str, Any]] = {}
    seen: set[int] = set()
    todo = [first]
    while todo and len(ifds) < MAX_TIFF_IFDS:
        off = todo.pop()
        if off in seen or off + count_len > n:
            continue
        seen.add(off)
        count = struct.unpack(count_fmt, data[off : off + count_len])[0]
        block_len = count_len + count * entry_size
        entries: list[dict[str, Any]] = []
        if off + block_len + off_len <= n:
            next_ptr = struct.unpack(off_fmt, data[off + block_len : off + block_len + off_len])[0]
        else:
            block_len = max(0, n - off - off_len)
            next_ptr = 0
        for i in range(count):
            e = off + count_len + i * entry_size
            if e + entry_size > n:
                break
            tag = struct.unpack(bo + "H", data[e : e + 2])[0]
            ftype = struct.unpack(bo + "H", data[e + 2 : e + 4])[0]
            fcount = struct.unpack(off_fmt, data[e + 4 : e + 4 + off_len])[0]
            value = data[e + 4 + off_len : e + entry_size]
            byte_size = fcount * _TIFF_TYPE_SIZES.get(ftype, 1)
            value_offset = None
            if byte_size > len(value):
                value_offset = struct.unpack(off_fmt, value[:off_len])[0]
            entries.append(
                {
                    "tag": tag,
                    "type": ftype,
                    "count": fcount,
                    "value": value,
                    "byte_size": byte_size,
                    "value_offset": value_offset,
                }
            )
        ifds[off] = {
            "count": count,
            "entries": entries,
            "next": next_ptr,
            "block_len": block_len,
        }
        if next_ptr:
            todo.append(next_ptr)
        for ent in entries:
            if ent["tag"] in (34665, 34853, 40965):
                ptr = struct.unpack(off_fmt, ent["value"][:off_len])[0]
                if ptr:
                    todo.append(ptr)
    return bo, bigtiff, ifds


def _tiff_entry_payload(data: bytes, ent: dict[str, Any]) -> bytes | None:
    """Fetch the referenced payload bytes for a TIFF entry, else None."""
    if ent["value_offset"] is None:
        return ent["value"][: ent["byte_size"]] if ent["byte_size"] <= len(ent["value"]) else None
    vo = ent["value_offset"]
    return data[vo : vo + ent["byte_size"]]


def inspect_tiff(data: bytes) -> tuple[bool, bool, list[str]]:
    """Walk the IFD chains (classic or BigTIFF) and report metadata tags."""
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    try:
        _bo, _big, ifds = _parse_tiff_ifds(data)
    except Exception:
        return False, False, ["not a valid TIFF"]
    if not ifds:
        return False, False, ["TIFF with no image file directories"]
    for _off, ifd in sorted(ifds.items()):
        for ent in ifd["entries"]:
            tag = ent["tag"]
            payload = _tiff_entry_payload(data, ent)
            hits = _contains_any(payload or b"", AI_META_HINTS + C2PA_MARKERS)
            if hits:
                if any(
                    h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth") for h in hits
                ):
                    has_c2pa = True
                has_ai = True
                findings.append(f"TIFF tag {tag}: {', '.join(hits[:6])}")
            name = _TIFF_META_TAG_NAMES.get(tag)
            if name:
                label = "sub-IFD" if tag in (34665, 34853, 40965) else "tag"
                findings.append(f"TIFF {label} {tag} ({name}) present")
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    if not findings:
        findings.append("no TIFF metadata tags found")
    return has_c2pa, has_ai or has_c2pa, findings


def _collect_tiff_sub_ifd_drops(
    off_fmt: str,
    off_len: int,
    ifds: dict[int, dict[str, Any]],
    data_len: int,
    ptr: int,
    drop_ranges: list[tuple[int, int]],
    drop_ifd_ranges: list[tuple[int, int]],
    visited: set[int],
) -> None:
    """Record drop ranges for an orphaned sub-IFD chain (ExifIFD/GPS)."""
    if not ptr or ptr in visited or ptr not in ifds:
        return
    visited.add(ptr)
    sub = ifds[ptr]
    drop_ifd_ranges.append((ptr, min(ptr + sub["block_len"] + off_len, data_len)))
    for ent in sub["entries"]:
        if ent["value_offset"] is not None:
            vo, vs = ent["value_offset"], ent["byte_size"]
            if vo + vs <= data_len:
                drop_ranges.append((vo, vo + vs))


def strip_tiff(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    """Drop TIFF metadata tags (classic or BigTIFF) without moving referenced data."""
    bo, bigtiff, ifds = _parse_tiff_ifds(data)
    if not ifds:
        raise ValueError("not a valid TIFF (no image file directories)")
    n = len(data)
    off_len = 8 if bigtiff else 4
    off_fmt = bo + ("Q" if bigtiff else "I")
    count_len = 8 if bigtiff else 2
    entry_size = 20 if bigtiff else 12
    actions: list[str] = []
    kept: dict[int, list[dict[str, Any]]] = {}
    drop_ranges: list[tuple[int, int]] = []
    drop_ifd_ranges: list[tuple[int, int]] = []

    for off, ifd in sorted(ifds.items()):
        keep_here: list[dict[str, Any]] = []
        for ent in ifd["entries"]:
            tag = ent["tag"]
            payload = _tiff_entry_payload(data, ent)
            marker_hit = bool(_contains_any(payload or b"", AI_META_HINTS + C2PA_MARKERS))
            if tag in (34665, 34853):
                ptr = struct.unpack(off_fmt, ent["value"][:off_len])[0]
                sub = ifds.get(ptr)
                if sub is not None:
                    sub_blob = data[ptr : min(ptr + sub["block_len"] + off_len, n)]
                    marker_hit = marker_hit or bool(
                        _contains_any(sub_blob, AI_META_HINTS + C2PA_MARKERS)
                    )
                    for sent in sub["entries"]:
                        s_payload = _tiff_entry_payload(data, sent)
                        if _contains_any(s_payload or b"", AI_META_HINTS + C2PA_MARKERS):
                            marker_hit = True
                            break
            drop = False
            if tag in _TIFF_DROP_TAGS:
                drop = strip_all_metadata or marker_hit
            elif marker_hit and tag not in _TIFF_KEEP_TAGS:
                drop = True
            if not drop:
                keep_here.append(ent)
                continue
            name = _TIFF_META_TAG_NAMES.get(tag)
            actions.append(
                f"drop TIFF tag {tag} ({name})" if name else f"drop TIFF tag {tag} (AI markers)"
            )
            if tag in (34665, 34853):
                ptr = struct.unpack(off_fmt, ent["value"][:off_len])[0]
                _collect_tiff_sub_ifd_drops(
                    off_fmt, off_len, ifds, n, ptr, drop_ranges, drop_ifd_ranges, set()
                )
            elif ent["value_offset"] is not None and ent["value_offset"] + ent["byte_size"] <= n:
                drop_ranges.append((ent["value_offset"], ent["value_offset"] + ent["byte_size"]))
        kept[off] = keep_here

    # Ranges still referenced from the root through kept entries must never be zeroed.
    reachable: set[int] = set()

    def _mark_reachable(off: int) -> None:
        if off in reachable or off not in ifds:
            return
        reachable.add(off)
        for ent in kept.get(off, []):
            if ent["tag"] in (34665, 34853, 40965):
                _mark_reachable(struct.unpack(off_fmt, ent["value"][:off_len])[0])
        if ifds[off]["next"]:
            _mark_reachable(ifds[off]["next"])

    root = (
        struct.unpack(off_fmt, data[16 - off_len : 16])[0]
        if bigtiff
        else struct.unpack(off_fmt, data[8 - off_len : 8])[0]
    )
    _mark_reachable(root)

    referenced: list[tuple[int, int]] = []
    for off in sorted(reachable):
        for ent in kept.get(off, []):
            if ent["value_offset"] is not None and ent["value_offset"] + ent["byte_size"] <= n:
                referenced.append((ent["value_offset"], ent["value_offset"] + ent["byte_size"]))
            if ent["tag"] in (34665, 34853, 40965):
                ptr = struct.unpack(off_fmt, ent["value"][:off_len])[0]
                sub = ifds.get(ptr)
                if sub is not None:
                    referenced.append((ptr, min(ptr + sub["block_len"] + off_len, n)))
                    for sent in sub["entries"]:
                        if sent["value_offset"] is not None:
                            vo = sent["value_offset"]
                            vs = sent["byte_size"]
                            if vo + vs <= n:
                                referenced.append((vo, vo + vs))

    for r_start, r_end in drop_ranges:
        if r_start >= r_end:
            continue
        overlap = False
        for ref_s, ref_e in referenced:
            if ref_s < r_end and ref_e > r_start:
                overlap = True
                break
        if not overlap:
            data = bytearray(data)
            data[r_start:r_end] = b"\x00" * (r_end - r_start)

    for r_start, r_end in drop_ifd_ranges:
        if r_start >= r_end:
            continue
        overlap = False
        for ref_s, ref_e in referenced:
            if ref_s < r_end and ref_e > r_start:
                overlap = True
                break
        if not overlap:
            data = bytearray(data)
            data[r_start:r_end] = b"\x00" * (r_end - r_start)

    # Patch each IFD block in place: kept entries copied verbatim, dropped
    # entries removed, block zero-padded to its original length.
    out = bytearray(data)
    for off, ifd in sorted(ifds.items()):
        block_start = off
        block_len = ifd["block_len"]
        block = bytearray(b"\x00" * block_len)
        cursor = 0
        cursor += count_len
        for ent in kept.get(off, []):
            e = bytearray(entry_size)
            e[0:2] = struct.pack(bo + "H", ent["tag"])
            e[2:4] = struct.pack(bo + "H", ent["type"])
            count_fmt = bo + ("Q" if bigtiff else "I")
            e[4 : 4 + off_len] = struct.pack(count_fmt, ent["count"])
            e[4 + off_len : entry_size] = ent["value"][: entry_size - 4 - off_len]
            block[cursor : cursor + entry_size] = bytes(e)
            cursor += entry_size
        kept_count = len(kept.get(off, []))
        block[0:count_len] = struct.pack(bo + ("Q" if bigtiff else "H"), kept_count)
        block[cursor : cursor + off_len] = struct.pack(off_fmt, ifd["next"] if kept_count else 0)
        out[block_start : block_start + block_len + off_len] = bytes(block) + b"\x00" * (
            block_len + off_len - len(block)
        )

    if not actions:
        actions.append("no TIFF metadata tags removed (already clean or none matched)")
    return bytes(out), actions


def clean_image(
    path: Path,
    dest: Path,
    *,
    strip_all_metadata: bool = True,
    synthid_dir: str | None = None,
    remove_synthid: bool = False,
    synthid_strength: float = 0.6,
    wmct_marker: bool = False,
) -> dict[str, Any]:
    data = path.read_bytes()
    fmt = detect_format(data)
    synthid_before = run_synthid_score(path, synthid_dir) if fmt in ("png", "jpeg") else None
    if fmt == "png":
        cleaned, actions = strip_png(data, strip_all_text=strip_all_metadata)
    elif fmt == "jpeg":
        cleaned, actions = strip_jpeg(data, strip_all_app=strip_all_metadata)
    elif fmt == "heif":
        cleaned, actions = strip_heic(data, strip_all=strip_all_metadata)
    elif fmt == "avif":
        cleaned, actions = strip_avif(data, strip_all=strip_all_metadata)
    elif fmt == "webp":
        cleaned, actions = strip_webp(data, strip_all_metadata=strip_all_metadata)
    elif fmt == "bmp":
        cleaned, actions = strip_bmp(data, strip_all_metadata=strip_all_metadata)
    elif fmt == "gif":
        cleaned, actions = strip_gif(data, strip_all_metadata=strip_all_metadata)
    elif fmt == "tiff":
        cleaned, actions = strip_tiff(data, strip_all_metadata=strip_all_metadata)
    else:
        raise ValueError(f"unsupported format: {fmt}")

    # Optional exiftool pass for residual tags
    atomic_write_bytes(dest, cleaned)
    exiftool = which("exiftool")
    if exiftool and strip_all_metadata:
        try:
            result = external_command.run_command(
                [
                    exiftool,
                    "-all=",
                    "-overwrite_original",
                    str(dest),
                ],
                timeout=60,
                output_limit=OPTIONAL_TOOL_OUTPUT_LIMIT,
            )
            if result.returncode == 0 and not (result.stdout_truncated or result.stderr_truncated):
                actions.append("exiftool -all= pass")
            else:
                detail = (result.stderr_text or result.stdout_text).strip()[:300]
                if result.stdout_truncated or result.stderr_truncated:
                    detail = "output exceeded safety limit"
                actions.append(f"exiftool failed (rc={result.returncode}): {detail}")
        except Exception as error:
            actions.append(f"exiftool failed: {error}")

    synthid_removal: dict[str, Any] | None = None
    if remove_synthid:
        if fmt != "png":
            raise ValueError(
                "SynthID removal currently supports PNG output; JPEG/HEIF/AVIF "
                "inputs are not supported"
            )
        if not 0.0 <= synthid_strength <= 1.0:
            raise ValueError("synthid_strength must be in [0, 1]")
        # Lazy import keeps the metadata-only CLI free of the raster/DCT stack
        # until removal is actually requested.
        from synthid_remove import apply_synthid_removal

        # Reads dest, applies band suppression, writes dest back in place.
        apply_synthid_removal(
            dest,
            dest,
            strength=synthid_strength,
        )
        synthid_removal = {
            "strategy": "synthid-band-dct",
            "strength": synthid_strength,
            "block_size": 8,
            "bytes_out": dest.stat().st_size,
            "note": "seed-independent mid-frequency band suppression (best-effort)",
        }
        actions.append(
            f"SynthID band removal: strength={synthid_strength} (seed-independent DCT suppression)"
        )

    if wmct_marker:
        if fmt != "png":
            actions.append("wmCt replacement marker skipped: PNG output only")
        else:
            # Read dest (post-strip/exiftool/synthid), inject the marker, and
            # write back so the truthful marker survives every prior pass.
            marked = add_wmct_marker(dest.read_bytes())
            atomic_write_bytes(dest, marked)
            actions.append(
                "wmCt replacement marker written (strip-without-replacement remains the default)"
            )
        wmct_marker_present = fmt == "png"
    else:
        wmct_marker_present = False

    after = inspect_image(dest, synthid_dir=synthid_dir)
    return {
        "input": str(path),
        "output": str(dest),
        "format": fmt,
        "actions": actions,
        "bytes_in": len(data),
        "bytes_out": dest.stat().st_size,
        "still_has_c2pa": after.has_c2pa,
        "still_has_ai_metadata": after.has_ai_metadata,
        "post_findings": after.findings,
        "synthid_before": synthid_before,
        "synthid_after": after.synthid,
        "synthid_removal": synthid_removal,
        "wmct_marker": wmct_marker_present,
    }
